### ISSUE TITLE
Wish: Right click context menu

### ISSUE THREAD

**Issue by JasonWHowell** [jonburchel/ScreenshotScrubber#1]
Would it be really complex to add a right click gesture? 

1. User selects text (highlights with their mouse).
2. Right click > Add text to the "Replace text" settings. 
3. Either a prompt appears, or the extension options opens to configure the "New text" value for the replacement text.
4. Run the scrubber on the web page again to replace other occurrences of the same text.

**Comment by jonburchel** [comment]
Thanks for getting the ball rolling with our first issue/idea @JasonWHowell!

I added an initial stab at this functionality in this commit:  https://github.com/jonburchel/ScreenshotScrubber/commit/0277fd206fad4ef6aae5719bdde24d8ebe7318c8

For now it clumsily prompts for replacement text, then Confirms() with an OK/Cancel confirmation (the only kind browser's natively support) whether you want to replace ALL or just the one occurrence.  Eventually I want to put that on a fancy little HTML dialog, and also allow you to select there whether you want to save it as a future default or just do a one-time replacement.  But at this point you should be able to select text and replace on the page, most of the time.  Sometimes it won't work if HTML stuff gets in the way of detecting the raw text string. But most of the time worked just as expected when I tested!
