### ISSUE TITLE
Wish: Work with Azure Cloud Shell

### ISSUE THREAD

**Issue by MatthewMWR** [jonburchel/ScreenshotScrubber#10]
Thanks for making Screenshot Scrubber. I am excited to start using it.

In many cases I am creating documentation with command line examples in Azure Cloud Shell (https://shell.azure.com). These examples are full of usernames, subscription IDs, etc. which would be ideal to replace with Screenshot Scrubber.

Unfortunately, whatever dynamic magic is behind cloud shell seems to mean that the console text does not exist in the static page/DOM. For example, using Screenshot Scrubber or even F12 tools I can't find the console text. I don't know how you would do it, but working with Azure Cloud Shell would be a super awesome scenario for the tool.

**Comment by jonburchel** [comment]
Hi @MatthewMWR, and thanks for the suggestion. I agree, this would be really nice to get fixed. Unfortunately, the approach we use in the tool to replace text requires the text exist in the raw source someplace to be replaced. In some cases like with the Azure PowerShell console, it isn't kept there, and I've been able to find no way to replace that text so far. If you do stumble on any clues to how we might do it with F12 explorations, I would love to update the tool with a fix to make it universal! Right now it works about 95% of the time, but there are edge cases like this where it just fails...
