### ISSUE TITLE
Recently, ScreenshotScrubber failed to replace text in some portal pages

### ISSUE THREAD

**Issue by halkazwini** [jonburchel/ScreenshotScrubber#11]
Hi Jon,

I love ScreenshotScrubber which made my life much easier with screenshots!

Unfortunately, recently, I couldn't replace text on some portal pages using ScreenshotScrubber. The tool used to replace text on these same pages without any issue! I'm not sure if it's something with the programming of those pages. Examples of pages that ScreenshotScrubber doesn't currently work with are the Virtual network and Public IP address.

I hope there is a solution for this issue!

Regards.

**Comment by jonburchel** [comment]
Thanks @halkazwini. The tool does work most of the time, but sometimes the text is embedded in such a way that it isn't found when the scrubber searches the source code, so there are some times when it simply doesn't work with some text. If you have an example of the text and page it fails from though, I'll have a look to see if there might be something wrong that I could fix to make it work in that scenario. You can respond here if you have more details and I'll look into it, even though I'll close the issue out for now.
