### ISSUE TITLE
Can't select an image to replace

### ISSUE THREAD

**Issue by asergaz** [jonburchel/ScreenshotScrubber#12]
Hi team,

I can't select an image to replace. It only allow me to stick with the option "remove: no new image"

![image](https://user-images.githubusercontent.com/22173500/219033164-afe13184-8bcb-4be1-88f2-674749d7171c.png)

**Comment by asergaz** [comment]
Ok I have worked around this. I have exported the Settings from Scrubber and then in the json file I replace the "replacementURL" with the image I want.  Then I import the settings with the modified json file.

It works with that workaround.

**Comment by jonburchel** [comment]
I've just updated the tool and it should fix this at least in my testing. Apologies for the long delay to fix it!!
