### ISSUE TITLE
Causes devops (dev.azure.com) to display a blank dialog for the 'main' display.

### ISSUE THREAD

**Issue by Blackmist** [jonburchel/ScreenshotScrubber#7]
If the extension is installed, and activated, I go to dev.azure.com and select work items. Displays the list of items. Clicking a link to open item details, I get a blank screen.
Same behavior for viewing the backlog or queries.

**Comment by jonburchel** [comment]
Sorry for my slow response @Blackmist.  Thank you for reporting this too!  I had similar reports around the same time for other sites, and made a change a while back that I believe corrected this.  When I tested now, the site seems to behave correctly without any issues.  I will close this issue out now but if it does persist for you please let me know and I will pick it up again.  I want to be sure it is not breaking any sites!  That is a high priority bug if so...
